services:
  front:
    build: ./front
    restart: on-failure
    ports:
      - "3000:5173"
    networks:
      - api-tier
    depends_on:
      - api
  api:
    build: ./api
    restart: on-failure
    networks:
      - api-tier

networks:
  api-tier:
